execute_process(COMMAND date -I OUTPUT_VARIABLE PACKAGE_DATE OUTPUT_STRIP_TRAILING_WHITESPACE)
message(STATUS "Configuration date: ${PACKAGE_DATE}")

set(CPACK_GENERATOR "ZIP")
set(CPACK_PACKAGE_FILE_NAME "${CMAKE_PROJECT_NAME} ${PACKAGE_DATE}")
include(CPack)
